### ISSUE TITLE
Can we add a hand presence sample?

### ISSUE THREAD

**Issue by zurgeg** [el-dee/panda3d-openvr#2]
I was working on this and couldn't figure out how to do hand presence. I figured it would be helpful if you could add a hand presence tutorial.
Thanks in advance.

**Comment by el-dee** [comment]
What do you mean "hand presence" ?

If that means tracking the controllers and represent them in world, you can look at the two examples, minimal and action. Both are attaching an instance of a model on each detected controllers so you can see where in the tracking space they are located.

If you follow the minimal example, you have to test the device class to know which device is actually a controllers, if you follow the action example, the manifest will bind the left and right controllers to the pose you have defined.

**Comment by zurgeg** [comment]
No, I mean using the grip, trigger and buttons to show your hands in the
virtual world.

**Comment by el-dee** [comment]
That's possible, but that requires much more work and that heavily depends on the type of your controller : You have to retrieve the analogue position of all the buttons that represent your fingers. For the Vive controller, only the trigger has an analogue sensor, the grip is a simple on/off button, ...

Once you have your input that should represent your fingers, you must have a rigged hand model with morph sliders for each fingers. You need to map the value you received from the controller to modify the slider and morph the hand in word.

**Comment by zurgeg** [comment]
I have a rigged hand model but I don't know how to rotate the bones in Panda3D. Could you help?

**Comment by zurgeg** [comment]
Adding a hand presence sample in a fork. This issue will be closed once I'm done!

**Comment by el-dee** [comment]
Thanks for taking care of this ! I don't have the time (and the knowledge) to do the sample right now, so it's really helpful

**Comment by zurgeg** [comment]
No problem! The only problem is the hand from Valve's samples are a little weird.

**Comment by zurgeg** [comment]
By the way, my fork is zurgeg/panda3d-openvr.

**Comment by zurgeg** [comment]
Update! Close to a keyboard and mouse controlled PC version. I'll tell you when it's in VR!

**Comment by zurgeg** [comment]
Old issue.
