### ISSUE TITLE
Can we add a Quest/Rift version?

### ISSUE THREAD

**Issue by zurgeg** [el-dee/panda3d-openvr#3]
Oculus's APIs are extremely complicated. I think that a Quest/Rift version could be helpful. The Quest version is what I'm working on right now (using [this](github.com/zurgeg/python-vrapi)) and Rift using pyovr shouldn't be that different (since it's made by the same person). Thanks!

**Comment by el-dee** [comment]
I don't see any benefit to use pyovr or Oculus API. pyovr is obsolete, runs only on Windows with Python2.7 and is not supported anymore and API is not the same at all than OpenVR (cmbruns did only the Python binding, they did not wrote the API)

As OpenVR supports out of the box the Quest and Rift, there is no added value I'm afraid.

**Comment by zurgeg** [comment]
Alright, closing this issue.

**Comment by zurgeg** [comment]
Whoops, it's already closed :).

**Comment by el-dee** [comment]
Sorry, I messed up the Oculus devices! OpenVR does indeed not support the Quest and the Rift. The upcoming standard OpenXR will do. And Panda will support in a future version OpenXR natively :)

**Comment by zurgeg** [comment]
Hold on does [this](https://developer.oculus.com/downloads/package/oculus-openxr-mobile-sdk/) mean that when OpenXR is finished, we will be able to use Oculus, SteamVR, and Quest with the same code?

**Comment by el-dee** [comment]
Well, that's what OpenXR promises :) Seeing that many manufacturers are moving to OpenXR that may be true.

**Comment by zurgeg** [comment]
When will support for OpenXR come? Thanks.
EDIT: If it helps, I'm working on bindings for OpenXR on the 3 major platforms (Quest, Rift, Steam).

**Comment by zurgeg** [comment]
Hey @el-dee, I found python bindings for OpenXR. Taking a look at them...
EDIT: It's `openxr`. I will note that you **need** the OpenXR for the particular platform (so Rift(S) OpenXR, Quest OpenXR, Index/Vive OpenXR).

**Comment by kukulski** [comment]
recently up & running on panda3d vs OSX -- loving what fast-startup is doing for my iteration speed. 
it would be _huge_ to be able to run on a quest

openXR API wouldn't do much to help that along

(though running vs löVR might be the way to go -- they even have hotloading support)
