### ISSUE TITLE
[Feature Request] OpenXR Support

### ISSUE THREAD

**Issue by zurgeg** [el-dee/panda3d-openvr#4]
The currently available standard for OpenXR gives extra versatility to VR applications by allowing for almost any VR system to be supported by a single app. This would be an incredibly helpful feature to add. Thanks!

**Comment by zurgeg** [comment]
Well, I found bindings for OpenXR, the problem is... I can't build it, as for the bindings, they are `openxr` on PyPI.

**Comment by zurgeg** [comment]
Update: It appears that OpenXR isn't actually a binding for OpenXR...

**Comment by el-dee** [comment]
Still no mature OpenXR binding for Python, I'm closing this for the moment
