### ISSUE TITLE
[Issue] Actions return None/0 data and no device path on Oculus Rift S

### ISSUE THREAD

**Issue by thetestgame** [el-dee/panda3d-openvr#7]
When trying to use actions with the Oculus Rift S controllers all data is either None/0 and has no device path. This can be demonstrated with the stock ralph sample. You can not walk around the environment. I also noticed stuttering with the compositor submit process when actions were enabled on the Rift S

**Comment by el-dee** [comment]
I don't own a Rift S so I can not easily debug, could you paste the full log when loading and testing the action or ralph sample ?

With the action sample, are there boxes where you controllers ought to be and do they move in sync ?

The binding are generic, but it could happen that one of the binding target is not supported by the Rift S and so cause the whole manifest to be rejected.

**Comment by thetestgame** [comment]
With the action sample I do see the boxes. Tracking seems to work fine on Oculus just not analog or digital inputs.

Here is the log from Ralph
```
D:\dev\panda3d-openvr\samples\ralph>python main.py
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)
Replicating left eye
Loading D:\dev\panda3d-openvr\samples\ralph\ralph_actions.json
```

**Comment by el-dee** [comment]
I see, the Oculus touch does not have a trackpad, which is used by the Ralph sample to move and turn around. When running the sample, you could open the SteamVR menu and use the edit custom bindings to remap the action to the actual inputs of the Oculus Touch :

The Axis2D.PrimaryThumbstick (or Axis2D.SecondaryThumbstick) should be activated and the position mapped to trackpadpos, also the click of Axis2D.PrimaryThumbstick (or Button.PrimaryThumbstick) should be mapped to trackpadclick

If that works, could you tell me what mapping did you use so I can create a proper binding for the oculus touch ?

**Comment by thetestgame** [comment]
I adjusted the thumbsticks to Trackpad pos and click. I am still not getting any response from the ralph demo. Going into the minimal though however shows input for the click just not the thumbstick axis now.

**Comment by el-dee** [comment]
The minimal sample only shows the button events, not the change of position of the trackpad or joystick.

Do you still have None as data and no device path for the trackpad_click and trackpad_pos action or just one of them or both are now returning data ?

The ralph sample requires that the user presses on the trackpad of the Vive controller to move and turn around. Are you also pressing on the thumbstick or do you just push it ?

**Comment by thetestgame** [comment]
I just double checked. I have None as data and no device path still. Pressing on the thumbstick and moving it does not change this.

**Comment by el-dee** [comment]
Looking at the few manifest files I could find for the oculus touch,  it seems that the mode in the binding file for the thumbstick shoud be 'joystick' and not 'trackpad'. Though some versions of the touch accept both...
It should also be possible to change that in the custom binding panel of SteamVR .

Could you tell me if this change the behavior ?

**Comment by zurgeg** [comment]
Ah, I've been having this same problem for a while! I always assumed it was an Oculus problem.

Anyway, I tested the sample code on a Vive, and it gives the same result?

**Comment by zurgeg** [comment]
@el-dee Are you using the SteamVR Beta? Actions seem to be broken for me entirely on SteamVR Beta...

**Comment by zurgeg** [comment]
@thetestgame Are you sure you bound the controls for Oculus Touch? I had to do that before it would give me anything but 0.

**Comment by el-dee** [comment]
> Anyway, I tested the sample code on a Vive, and it gives the same result?

@zurgeg I'm not sure I understand, do you have problems with the Vive Controller or does it work fine with the Vive ?

> Are you using the SteamVR Beta? Actions seem to be broken for me entirely on SteamVR Beta...

I have not tested with Steam VR Beta, I will try to find some time and give it a test.

I have found more information about the manifest files (the documentation is scarce) I will try and update the manifest files. But knowing if binding the controller with the joystick did solve the problem would be a huge help !

**Comment by zurgeg** [comment]
@el-dee So, I figured a couple of things out:
1. SteamVR does not seem to like it if you use the new binding UI, if you use the old one, it seems to work fine
2. I've found that the couple of times I had this problem, it always seems to be because I did my bindings wrong, I will try exporting my binding JSON generated from SteamVR later and uploading it here
3. For some reason, random things seem to either make Oculus flip out and crash, make SteamVR flip out and crash, or make the program flip out and crash. It only seems to happen on Oculus headsets though. For instance, once, entering the binding UI crashed the entire oculus software.
Anyway, I finally got this to work, I just needed to go into `Add Poses` and add my poses here, I wasn't doing that and that was the main problem for me.

**Comment by el-dee** [comment]
@thetestgame  Did you check with 'joystick' ? 
@zurgeg  Were you able to export your bindings for the Rift ? If so could you upload them or send them to me, I will compare them with the few information I gathered around and, if they match, I will be able to make manifest for several controllers and HMD !

**Comment by zurgeg** [comment]
@el-dee It seemed to be Steam just being Steam, if you have "Show Advanced Options" on it'll show up, check the Steam workshop, there may or may not be a ton of bindings there from the user "zurgeg"

**Comment by el-dee** [comment]
Now the samples use the default action manifest provided by Valve, they should work with all the common controllers.
